# Generated by Django 3.2.13 on 2022-07-19 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0172_drop_media_to_remove"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmedia",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="product.product",
            ),
        ),
    ]
